import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../Components/Header'
import Footer from '../Components/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Vacayou – Wellness & Active Travel That Moves You</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
          <Header/>
      </header>
      <main className={styles.main}>
        <section className={styles.tripcontainer}>
          <div className="container mx-auto sm:px-6 lg:px-8">
            <div className={styles.tripcontainer1}>
              <h2 className="text-center mb-4">MAINE'S ACADIA NATIONAL PARK: CYCLE THROUGH COASTAL SCENERY &amp; RUGGED BEAUTY</h2>
                <div className="grid">
                  <div className="p-6">
                    <div className="items-center">
                      <div className="ml-4 text-lg leading-7 font-semibold text-center"><a href="/dateSelection" className={styles.availabilitybtn}>Book Now</a></div>
                    </div>
                  </div>
                </div>
            </div>
          </div>
        </section>
        <section className={styles.highlights}>
            <div className="container mx-auto sm:px-6 lg:px-8">
              <div className={styles.pckg}>
                <h3>Highlights</h3>
                <p>While the rugged beauty of Acadia National Park naturally gets the headlines, there is so much more to cycling in Maine than just one of the nation’s most beloved parks. From the rugged coastal scenery to quintessential New England fishing villages and inspiring lighthouses to watching the sun rise above the Atlantic Ocean, Maine offers something for every level of cyclist. During this cycling tour powered by Intrepid Travel, spend your days riding quiet and beautiful tree-lined roads and your evenings enjoying some of America’s finest seafood cuisine—the perfect antidote to busy city life.</p>
              </div>
            </div>
        </section>
      </main>
      <Footer />
    </div>
  )
}
