import React, { Component } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../Components/Header'
import Footer from '../Components/Footer'
import phone from '../public/images/phone-call.svg';
import chat from '../public/images/chat.svg';
import PckgImg from '../public/images/q_70 (4) (1).jpg';
import Tick from '../public/images/check.png';
// import BookingSummary from '../Components/bookingSummary';

export default class Success extends Component {
    constructor(props) {
        super(props);
        this.state = {
            pDateData: '',
            bData: '',
        };
    }

    static async getInitialProps() {
        const tripDate = new Date();
        const eTripDate = tripDate.toString().replace(/ /g,"-").replace(/.{4}/, '').slice(0, -40);
        const res = await fetch(`https://staging.bookingadmin.vacayou.com/api/getpackagedetailbyholidayid/96/${eTripDate}/${eTripDate}`)
        const offers = await res.json()
        //console.log(offers);
        return { offers }
      }
      componentWillMount() {
        this.setState({
          offers: this.props.offers
        })
      }
      componentDidMount() {
        this.setState({
            pDateData: localStorage.getItem('form'),
            bData: localStorage.getItem('bId')
        })
      }
   
    render() {
        const offerList = this.state.offers;
        const spDate = this.state.pDateData.split('"');
        console.log(this.state.pDateData);
        console.log(spDate);
        const final_base_price = +spDate[23];
        const taxes = +spDate[27];
        // const max_children = spDate[35];
        // const max_infants = spDate[39];
        const bIData = this.state.bData.split('"');
        console.log(bIData);
        const total_price = bIData[4];

        return (
            <div className={styles.container}>
            <Head>
                <title>Vacayou – Wellness & Active Travel That Moves You</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header>
                <Header/>
            </header>
            <main className={styles.main}>
                <section className={styles.tripcontainer} style={{backgroundImage:`url(${offerList.package_image} )`}}>
                <div className="container mx-auto sm:px-6 lg:px-8">
                    <div className={styles.tripcontainer1}>
                    <h2 className="text-center mb-4">{offerList.package_name}</h2>
                    </div>
                </div>
                </section>
                <section className="trip">
                    <div className="container mx-auto sm:px-6 lg:px-8">
                        <div className="grid grid-rows-1 grid-flow-col gap-4 trip-container">
                            <div className="trips col-span-1">
                                <h2>Check Your Email</h2>
                                <p>Success! We have everything we need, and our team will confirm your booking within 24 hours. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
                                <div className="need-assistance">
                                    <h4>Need Assistance</h4>
                                    <p>Our Travel Concierge team is here to help!</p>
                                    <p className="info flex items-center"><Image src={phone} /> <a href="tel:833 822 2968">833 822 2968</a></p>
                                    <p className="info flex items-center"><Image src={chat} /> <a href="#">Chat with us</a></p>
                                </div>
                            </div>
                            <div className="booking-details col-span-1">
                                <div className="selected-offer">
                                    <h4>
                                        {spDate[15]}
                                    </h4>
                                    <div className="sel-offer flex items-center">
                                        <div className="trip-info">
                                            <div className="flex items-center" style={{paddingBottom: 10 + 'px'}}>
                                                <p>Offer: </p>
                                                <p style={{fontWeight: 500, marginLeft: 5 + 'px', fontSize: 16 + 'px'}}>{spDate[15]}</p>
                                            </div>
                                            <div className="flex items-center">
                                                <p>Travel Dates: </p>
                                                <p style={{fontWeight: 500, marginLeft: 5 + 'px', fontSize: 16 + 'px'}}>{spDate[3]} - {spDate[7]}</p>
                                            </div>
                                        </div>
                                        <div className="trip-img" style={{backgroundImage:`url(${offerList.package_image} )`}}>
                                            {/* <Image src={PckgImg} /> */}
                                        </div>
                                    </div>
                                    <p className="pckg-info">Included in Your Package:</p>
                                    <ul>
                                        <li><Image src={Tick} /> Luxurious accomodations for two in a Signature room with one king size bed</li>
                                        <li><Image src={Tick} /> A 50-minute Mirbeau Signature Massage per person</li>
                                        <li><Image src={Tick} /> Special welcome amenity</li>
                                    </ul>
                                </div>
                                <div className="booking-summary">
                                    <h4>
                                        Booking Summary
                                    </h4>
                                    <p className="flex items-center justify-between">
                                        <span>Base Price</span>
                                        <span>${final_base_price}</span>
                                    </p>
                                    <p className="flex items-center justify-between">
                                        <span>Taxes & Fees*</span>
                                        <span>${taxes}</span>
                                    </p>
                                    <p className="flex items-center justify-between">
                                        <span>Total</span>
                                        <span>${total_price}</span>
                                    </p>
                                </div>
                                <div className="tnc">
                                    <p>*Taxes and Fees are an estimate and may vary slightly. There may also be additional fees due to the provider which are documented in the package terms and conditions.</p>
                                    <p>Any customizations are not reflected in price and we will reach out to you within 24 hours to confirm your request.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </main>
            <Footer />
            </div>
        );
    }
}
